using Dotmim.Sync.Builders;
using Dotmim.Sync.DatabaseStringParsers;
using Dotmim.Sync.Manager;
using Dotmim.Sync.Oracle.Manager;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Dotmim.Sync.Oracle.Builders
{
    /// <summary>
    /// Builds the table, tracking table and triggers for the Oracle provider.
    /// This provider does not use stored procedures; all CRUD/select logic is inline text
    /// generated by <see cref="OracleObjectNames"/>.
    /// </summary>
    public class OracleTableBuilder : DbTableBuilder
    {
        private readonly OracleObjectNames oracleObjectNames;
        private readonly DbTableNames tableNames;
        private readonly DbTableNames trackingTableNames;

        /// <inheritdoc cref="OracleTableBuilder"/>
        public OracleTableBuilder(SyncTable tableDescription, ScopeInfo scopeInfo)
            : base(tableDescription, scopeInfo)
        {
            this.oracleObjectNames = new OracleObjectNames(tableDescription, scopeInfo);

            var leftQuote = OracleObjectNames.LeftQuoteChar;
            var rightQuote = OracleObjectNames.RightQuoteChar;
            var schema = tableDescription.SchemaName ?? string.Empty;

            var tableParser = new ObjectParser(tableDescription.TableName, leftQuote, rightQuote);
            this.tableNames = new DbTableNames(
                leftQuote,
                rightQuote,
                tableDescription.TableName,
                schema.Length > 0 ? $"{schema}.{tableDescription.TableName}" : tableDescription.TableName,
                tableParser.NormalizedShortName,
                this.oracleObjectNames.TableQuotedFullName,
                tableParser.QuotedShortName,
                schema);

            var trackingParser = new ObjectParser(this.oracleObjectNames.TrackingTableName, leftQuote, rightQuote);
            this.trackingTableNames = new DbTableNames(
                leftQuote,
                rightQuote,
                this.oracleObjectNames.TrackingTableName,
                schema.Length > 0 ? $"{schema}.{this.oracleObjectNames.TrackingTableName}" : this.oracleObjectNames.TrackingTableName,
                trackingParser.NormalizedShortName,
                this.oracleObjectNames.TrackingTableQuotedFullName,
                trackingParser.QuotedShortName,
                schema);
        }

        /// <inheritdoc/>
        public override DbTableNames GetParsedTableNames() => this.tableNames;

        /// <inheritdoc/>
        public override DbTableNames GetParsedTrackingTableNames() => this.trackingTableNames;

        /// <inheritdoc/>
        public override DbColumnNames GetParsedColumnNames(SyncColumn column)
        {
            var columnParser = new ObjectParser(column.ColumnName, OracleObjectNames.LeftQuoteChar, OracleObjectNames.RightQuoteChar);
            return new DbColumnNames(columnParser.QuotedShortName, columnParser.NormalizedShortName);
        }

        // ----------------------------------------------------------------------------------------
        // Schema (Oracle schema == user; not created here)
        // ----------------------------------------------------------------------------------------

        /// <inheritdoc/>
        public override Task<DbCommand> GetCreateSchemaCommandAsync(DbConnection connection, DbTransaction transaction)
        {
            // Oracle "schema" is a user; the provider does not create users. No-op.
            var command = connection.CreateCommand();
            command.Transaction = transaction;
            command.CommandText = "BEGIN NULL; END;";
            return Task.FromResult(command);
        }

        /// <inheritdoc/>
        public override Task<DbCommand> GetExistsSchemaCommandAsync(DbConnection connection, DbTransaction transaction)
        {
            var command = connection.CreateCommand();
            command.Transaction = transaction;
            command.CommandText = "SELECT COUNT(*) FROM ALL_USERS WHERE USERNAME = :userName";

            var parameter = command.CreateParameter();
            parameter.ParameterName = ":userName";
            parameter.Value = string.IsNullOrEmpty(this.TableDescription.SchemaName) ? connection.Database : this.TableDescription.SchemaName;
            command.Parameters.Add(parameter);

            return Task.FromResult(command);
        }

        // ----------------------------------------------------------------------------------------
        // Base table
        // ----------------------------------------------------------------------------------------

        /// <inheritdoc/>
        public override Task<DbCommand> GetCreateTableCommandAsync(DbConnection connection, DbTransaction transaction)
        {
            var stringBuilder = new StringBuilder();
            stringBuilder.AppendLine($"CREATE TABLE {this.oracleObjectNames.TableQuotedFullName} (");

            var comma = string.Empty;
            foreach (var column in this.TableDescription.Columns)
            {
                var columnType = GetOracleColumnTypeString(column);
                var nullable = column.AllowDBNull ? "NULL" : "NOT NULL";
                stringBuilder.AppendLine($"{comma}  \"{column.ColumnName}\" {columnType} {nullable}");
                comma = ",";
            }

            var pkColumns = string.Join(", ", this.TableDescription.GetPrimaryKeysColumns().Select(c => $"\"{c.ColumnName}\""));
            if (!string.IsNullOrEmpty(pkColumns))
                stringBuilder.AppendLine($",  CONSTRAINT \"PK_{this.oracleObjectNames.TableName}\" PRIMARY KEY ({pkColumns})");

            stringBuilder.AppendLine(")");

            var command = connection.CreateCommand();
            command.Transaction = transaction;
            command.CommandText = stringBuilder.ToString();
            return Task.FromResult(command);
        }

        /// <inheritdoc/>
        public override Task<DbCommand> GetExistsTableCommandAsync(DbConnection connection, DbTransaction transaction)
            => Task.FromResult(this.CreateExistsTableCommand(connection, transaction, this.TableDescription.TableName));

        /// <inheritdoc/>
        public override Task<DbCommand> GetDropTableCommandAsync(DbConnection connection, DbTransaction transaction)
        {
            var command = connection.CreateCommand();
            command.Transaction = transaction;
            command.CommandText = $"DROP TABLE {this.oracleObjectNames.TableQuotedFullName}";
            return Task.FromResult(command);
        }

        /// <inheritdoc/>
        public override Task<DbCommand> GetExistsColumnCommandAsync(string columnName, DbConnection connection, DbTransaction transaction)
        {
            var command = connection.CreateCommand();
            command.Transaction = transaction;
            command.CommandText = "SELECT COUNT(*) FROM USER_TAB_COLUMNS WHERE TABLE_NAME = :tableName AND COLUMN_NAME = :columnName";

            var tableParam = command.CreateParameter();
            tableParam.ParameterName = ":tableName";
            tableParam.Value = this.TableDescription.TableName;
            command.Parameters.Add(tableParam);

            var columnParam = command.CreateParameter();
            columnParam.ParameterName = ":columnName";
            columnParam.Value = columnName;
            command.Parameters.Add(columnParam);

            return Task.FromResult(command);
        }

        /// <inheritdoc/>
        public override Task<DbCommand> GetAddColumnCommandAsync(string columnName, DbConnection connection, DbTransaction transaction)
        {
            var column = this.TableDescription.Columns.FirstOrDefault(c => string.Equals(c.ColumnName, columnName, StringComparison.OrdinalIgnoreCase))
                ?? throw new Exception($"Column {columnName} does not exist in table {this.TableDescription.TableName}");

            var columnType = GetOracleColumnTypeString(column);
            var nullable = column.AllowDBNull ? "NULL" : "NOT NULL";

            var command = connection.CreateCommand();
            command.Transaction = transaction;
            command.CommandText = $"ALTER TABLE {this.oracleObjectNames.TableQuotedFullName} ADD (\"{columnName}\" {columnType} {nullable})";
            return Task.FromResult(command);
        }

        /// <inheritdoc/>
        public override Task<DbCommand> GetDropColumnCommandAsync(string columnName, DbConnection connection, DbTransaction transaction)
        {
            var command = connection.CreateCommand();
            command.Transaction = transaction;
            command.CommandText = $"ALTER TABLE {this.oracleObjectNames.TableQuotedFullName} DROP COLUMN \"{columnName}\"";
            return Task.FromResult(command);
        }

        // ----------------------------------------------------------------------------------------
        // Stored procedures : not used by the Oracle provider
        // ----------------------------------------------------------------------------------------

        /// <inheritdoc/>
        public override Task<DbCommand> GetExistsStoredProcedureCommandAsync(DbStoredProcedureType storedProcedureType, SyncFilter filter, DbConnection connection, DbTransaction transaction)
            => Task.FromResult<DbCommand>(null);

        /// <inheritdoc/>
        public override Task<DbCommand> GetCreateStoredProcedureCommandAsync(DbStoredProcedureType storedProcedureType, SyncFilter filter, DbConnection connection, DbTransaction transaction)
            => Task.FromResult<DbCommand>(null);

        /// <inheritdoc/>
        public override Task<DbCommand> GetDropStoredProcedureCommandAsync(DbStoredProcedureType storedProcedureType, SyncFilter filter, DbConnection connection, DbTransaction transaction)
            => Task.FromResult<DbCommand>(null);

        // ----------------------------------------------------------------------------------------
        // Tracking table
        // ----------------------------------------------------------------------------------------

        /// <inheritdoc/>
        public override Task<DbCommand> GetCreateTrackingTableCommandAsync(DbConnection connection, DbTransaction transaction)
        {
            var command = connection.CreateCommand();
            command.Transaction = transaction;
            command.CommandText = this.oracleObjectNames.CreateTrackingTableScript(GetOracleColumnTypeString);
            return Task.FromResult(command);
        }

        /// <inheritdoc/>
        public override Task<DbCommand> GetDropTrackingTableCommandAsync(DbConnection connection, DbTransaction transaction)
        {
            var command = connection.CreateCommand();
            command.Transaction = transaction;
            command.CommandText = $"DROP TABLE {this.oracleObjectNames.TrackingTableQuotedFullName}";
            return Task.FromResult(command);
        }

        /// <inheritdoc/>
        public override Task<DbCommand> GetExistsTrackingTableCommandAsync(DbConnection connection, DbTransaction transaction)
            => Task.FromResult(this.CreateExistsTableCommand(connection, transaction, this.oracleObjectNames.TrackingTableName));

        // ----------------------------------------------------------------------------------------
        // Triggers
        // ----------------------------------------------------------------------------------------

        /// <inheritdoc/>
        public override Task<DbCommand> GetExistsTriggerCommandAsync(DbTriggerType triggerType, DbConnection connection, DbTransaction transaction)
        {
            var command = connection.CreateCommand();
            command.Transaction = transaction;
            command.CommandText = "SELECT COUNT(*) FROM USER_TRIGGERS WHERE TRIGGER_NAME = :triggerName";

            var parameter = command.CreateParameter();
            parameter.ParameterName = ":triggerName";
            parameter.Value = this.oracleObjectNames.GetTriggerCommandName(triggerType);
            command.Parameters.Add(parameter);

            return Task.FromResult(command);
        }

        /// <inheritdoc/>
        public override Task<DbCommand> GetCreateTriggerCommandAsync(DbTriggerType triggerType, DbConnection connection, DbTransaction transaction)
        {
            var command = connection.CreateCommand();
            command.Transaction = transaction;
            command.CommandText = this.oracleObjectNames.CreateTriggerScript(triggerType);
            return Task.FromResult(command);
        }

        /// <inheritdoc/>
        public override Task<DbCommand> GetDropTriggerCommandAsync(DbTriggerType triggerType, DbConnection connection, DbTransaction transaction)
        {
            var command = connection.CreateCommand();
            command.Transaction = transaction;
            command.CommandText = $"DROP TRIGGER \"{this.oracleObjectNames.GetTriggerCommandName(triggerType)}\"";
            return Task.FromResult(command);
        }

        // ----------------------------------------------------------------------------------------
        // Schema discovery
        // ----------------------------------------------------------------------------------------

        /// <inheritdoc/>
        public override async Task<IEnumerable<SyncColumn>> GetColumnsAsync(DbConnection connection, DbTransaction transaction)
        {
            var columns = new List<SyncColumn>();

            var command = connection.CreateCommand();
            command.Transaction = transaction;

            // USER_TAB_COLS (not USER_TAB_COLUMNS) exposes VIRTUAL_COLUMN; virtual (computed)
            // columns must be flagged so they are excluded from sync DML on every side.
            command.CommandText = @"
                SELECT COLUMN_NAME, DATA_TYPE, DATA_LENGTH, DATA_PRECISION, DATA_SCALE, NULLABLE, CHAR_LENGTH, VIRTUAL_COLUMN
                FROM USER_TAB_COLS
                WHERE TABLE_NAME = :tableName AND HIDDEN_COLUMN = 'NO'
                ORDER BY COLUMN_ID";

            var parameter = command.CreateParameter();
            parameter.ParameterName = ":tableName";
            parameter.Value = this.TableDescription.TableName;
            command.Parameters.Add(parameter);

            var alreadyOpened = connection.State == ConnectionState.Open;
            try
            {
                if (!alreadyOpened)
                    await connection.OpenAsync().ConfigureAwait(false);

                using var reader = await command.ExecuteReaderAsync().ConfigureAwait(false);
                while (await reader.ReadAsync().ConfigureAwait(false))
                {
                    var columnName = reader.GetString(0);
                    var dataType = reader.GetString(1);
                    var dataLength = await reader.IsDBNullAsync(2).ConfigureAwait(false) ? 0 : Convert.ToInt32(reader.GetValue(2));
                    var precision = await reader.IsDBNullAsync(3).ConfigureAwait(false) ? (byte)0 : Convert.ToByte(reader.GetValue(3));
                    var scale = await reader.IsDBNullAsync(4).ConfigureAwait(false) ? (byte)0 : Convert.ToByte(reader.GetValue(4));
                    var allowNull = reader.GetString(5) == "Y";
                    var charLength = await reader.IsDBNullAsync(6).ConfigureAwait(false) ? 0 : Convert.ToInt32(reader.GetValue(6));
                    var isVirtual = !await reader.IsDBNullAsync(7).ConfigureAwait(false) && reader.GetString(7) == "YES";

                    var column = new SyncColumn(columnName)
                    {
                        OriginalTypeName = dataType,
                        AllowDBNull = allowNull,
                        MaxLength = dataType.IndexOf("CHAR", StringComparison.OrdinalIgnoreCase) >= 0 ? charLength : dataLength,
                        Precision = precision,
                        Scale = scale,
                        IsAutoIncrement = false,
                        IsCompute = isVirtual,
                    };

                    column.SetType(GetManagedType(dataType, precision, scale, dataLength));

                    columns.Add(column);
                }
            }
            finally
            {
                if (!alreadyOpened && connection.State == ConnectionState.Open)
                    await connection.CloseAsync().ConfigureAwait(false);
            }

            return columns;
        }

        /// <inheritdoc/>
        public override async Task<IEnumerable<SyncColumn>> GetPrimaryKeysAsync(DbConnection connection, DbTransaction transaction)
        {
            var primaryKeys = new List<SyncColumn>();

            var command = connection.CreateCommand();
            command.Transaction = transaction;
            command.CommandText = @"
                SELECT cols.COLUMN_NAME
                FROM USER_CONSTRAINTS cons
                JOIN USER_CONS_COLUMNS cols ON cons.CONSTRAINT_NAME = cols.CONSTRAINT_NAME
                WHERE cons.TABLE_NAME = :tableName AND cons.CONSTRAINT_TYPE = 'P'
                ORDER BY cols.POSITION";

            var parameter = command.CreateParameter();
            parameter.ParameterName = ":tableName";
            parameter.Value = this.TableDescription.TableName;
            command.Parameters.Add(parameter);

            var alreadyOpened = connection.State == ConnectionState.Open;
            try
            {
                if (!alreadyOpened)
                    await connection.OpenAsync().ConfigureAwait(false);

                using var reader = await command.ExecuteReaderAsync().ConfigureAwait(false);
                while (await reader.ReadAsync().ConfigureAwait(false))
                {
                    var columnName = reader.GetString(0);
                    var column = this.TableDescription.Columns.FirstOrDefault(c => string.Equals(c.ColumnName, columnName, StringComparison.OrdinalIgnoreCase))
                        ?? new SyncColumn(columnName);
                    primaryKeys.Add(column);
                }
            }
            finally
            {
                if (!alreadyOpened && connection.State == ConnectionState.Open)
                    await connection.CloseAsync().ConfigureAwait(false);
            }

            return primaryKeys;
        }

        /// <inheritdoc/>
        public override async Task<IEnumerable<DbRelationDefinition>> GetRelationsAsync(DbConnection connection, DbTransaction transaction)
        {
            var relations = new List<DbRelationDefinition>();

            var command = connection.CreateCommand();
            command.Transaction = transaction;
            command.CommandText = @"
                SELECT c.CONSTRAINT_NAME, c.TABLE_NAME, c.R_CONSTRAINT_NAME, rc.TABLE_NAME AS REFERENCED_TABLE_NAME
                FROM USER_CONSTRAINTS c
                JOIN USER_CONSTRAINTS rc ON c.R_CONSTRAINT_NAME = rc.CONSTRAINT_NAME
                WHERE c.CONSTRAINT_TYPE = 'R' AND c.TABLE_NAME = :tableName";

            var parameter = command.CreateParameter();
            parameter.ParameterName = ":tableName";
            parameter.Value = this.TableDescription.TableName;
            command.Parameters.Add(parameter);

            var alreadyOpened = connection.State == ConnectionState.Open;
            try
            {
                if (!alreadyOpened)
                    await connection.OpenAsync().ConfigureAwait(false);

                var foreignKeys = new List<(string ConstraintName, string TableName, string ReferencedConstraint, string ReferencedTable)>();
                using (var reader = await command.ExecuteReaderAsync().ConfigureAwait(false))
                {
                    while (await reader.ReadAsync().ConfigureAwait(false))
                    {
                        foreignKeys.Add((reader.GetString(0), reader.GetString(1), reader.GetString(2), reader.GetString(3)));
                    }
                }

                foreach (var fk in foreignKeys)
                {
                    var relation = new DbRelationDefinition
                    {
                        ForeignKey = fk.ConstraintName,
                        TableName = fk.TableName,
                        ReferenceTableName = fk.ReferencedTable,
                    };

                    var columnsCommand = connection.CreateCommand();
                    columnsCommand.Transaction = transaction;
                    columnsCommand.CommandText = @"
                        SELECT k.COLUMN_NAME, k.POSITION, r.COLUMN_NAME AS REFERENCED_COLUMN_NAME
                        FROM USER_CONS_COLUMNS k
                        JOIN USER_CONS_COLUMNS r ON r.CONSTRAINT_NAME = :referencedConstraintName AND r.POSITION = k.POSITION
                        WHERE k.CONSTRAINT_NAME = :constraintName
                        ORDER BY k.POSITION";

                    var conParam = columnsCommand.CreateParameter();
                    conParam.ParameterName = ":constraintName";
                    conParam.Value = fk.ConstraintName;
                    columnsCommand.Parameters.Add(conParam);

                    var refConParam = columnsCommand.CreateParameter();
                    refConParam.ParameterName = ":referencedConstraintName";
                    refConParam.Value = fk.ReferencedConstraint;
                    columnsCommand.Parameters.Add(refConParam);

                    using (var columnsReader = await columnsCommand.ExecuteReaderAsync().ConfigureAwait(false))
                    {
                        while (await columnsReader.ReadAsync().ConfigureAwait(false))
                        {
                            relation.Columns.Add(new DbRelationColumnDefinition
                            {
                                KeyColumnName = columnsReader.GetString(0),
                                Order = Convert.ToInt32(columnsReader.GetValue(1)),
                                ReferenceColumnName = columnsReader.GetString(2),
                            });
                        }
                    }

                    if (relation.Columns.Count > 0)
                        relations.Add(relation);
                }
            }
            finally
            {
                if (!alreadyOpened && connection.State == ConnectionState.Open)
                    await connection.CloseAsync().ConfigureAwait(false);
            }

            return relations;
        }

        // ----------------------------------------------------------------------------------------
        // Helpers
        // ----------------------------------------------------------------------------------------
        private DbCommand CreateExistsTableCommand(DbConnection connection, DbTransaction transaction, string tableName)
        {
            var command = connection.CreateCommand();
            command.Transaction = transaction;
            command.CommandText = "SELECT COUNT(*) FROM USER_TABLES WHERE TABLE_NAME = :tableName";

            var parameter = command.CreateParameter();
            parameter.ParameterName = ":tableName";
            parameter.Value = tableName;
            command.Parameters.Add(parameter);

            return command;
        }

        /// <summary>
        /// Maps a <see cref="SyncColumn"/> to an Oracle column type declaration, based on the managed
        /// <see cref="DbType"/> (works regardless of the source provider).
        /// </summary>
        internal static string GetOracleColumnTypeString(SyncColumn column)
        {
            // When the schema was read from an Oracle database, national character types must be
            // preserved exactly: a VARCHAR2 tracking-table PK column UNIONed against an NVARCHAR2
            // base column makes the _changes query fail with ORA-12704 (character set mismatch).
            // Oracle reports these names in uppercase; other providers use different names/casings
            // (e.g. SQL Server "nvarchar"), so an ordinal match only triggers for Oracle-origin schemas.
            switch (column.OriginalTypeName)
            {
                case "NVARCHAR2":
                    return column.MaxLength > 0 && column.MaxLength <= 2000 ? $"NVARCHAR2({column.MaxLength})" : "NCLOB";
                case "NCHAR":
                    return column.MaxLength > 0 && column.MaxLength <= 1000 ? $"NCHAR({column.MaxLength})" : "NCHAR(1)";
                case "NCLOB":
                    return "NCLOB";
                default:
                    break;
            }

            switch (column.GetDbType())
            {
                case DbType.Boolean:
                    return "NUMBER(1)";
                case DbType.Byte:
                case DbType.SByte:
                    return "NUMBER(3)";
                case DbType.Int16:
                case DbType.UInt16:
                    return "NUMBER(5)";
                case DbType.Int32:
                case DbType.UInt32:
                    return "NUMBER(10)";
                case DbType.Int64:
                case DbType.UInt64:
                    return "NUMBER(19)";
                case DbType.Single:
                    return "BINARY_FLOAT";
                case DbType.Double:
                    return "BINARY_DOUBLE";
                case DbType.Decimal:
                case DbType.VarNumeric:
                case DbType.Currency:
                    return column.Precision > 0
                        ? $"NUMBER({Math.Min((int)column.Precision, 38)},{Math.Min((int)column.Scale, 38)})"
                        : "NUMBER(38,18)";
                case DbType.Date:
                    return "DATE";
                case DbType.Time:
                case DbType.DateTime:
                case DbType.DateTime2:
                    return "TIMESTAMP";
                case DbType.DateTimeOffset:
                    return "TIMESTAMP WITH TIME ZONE";
                case DbType.Guid:
                    return "RAW(16)";
                case DbType.Binary:
                    return column.MaxLength > 0 && column.MaxLength <= 2000 ? $"RAW({column.MaxLength})" : "BLOB";
                case DbType.AnsiStringFixedLength:
                case DbType.StringFixedLength:
                    return column.MaxLength > 0 && column.MaxLength <= 2000 ? $"CHAR({column.MaxLength})" : "CHAR(1)";
                case DbType.Xml:
                    return "CLOB";
                case DbType.String:
                case DbType.AnsiString:
                default:
                    return column.MaxLength > 0 && column.MaxLength <= 4000 ? $"VARCHAR2({column.MaxLength})" : "CLOB";
            }
        }

        /// <summary>
        /// Maps an Oracle native type name to a managed CLR type (used when reading an existing schema).
        /// RAW(16) maps to <see cref="Guid"/> because that is how this provider stores GUIDs
        /// (same heuristic as MySQL's char(36) → Guid).
        /// </summary>
        internal static Type GetManagedType(string oracleType, byte precision, byte scale, int dataLength = 0)
        {
            var type = oracleType.ToUpperInvariant();

            if (type.StartsWith("TIMESTAMP", StringComparison.Ordinal))
                return type.Contains("TIME ZONE") ? typeof(DateTimeOffset) : typeof(DateTime);

            return type switch
            {
                "NUMBER" => scale > 0
                    ? typeof(decimal)
                    : precision == 0 ? typeof(decimal)
                    : precision <= 4 ? typeof(short)
                    : precision <= 9 ? typeof(int)
                    : precision <= 18 ? typeof(long)
                    : typeof(decimal),
                "FLOAT" => typeof(decimal),
                "BINARY_FLOAT" => typeof(float),
                "BINARY_DOUBLE" => typeof(double),
                "DATE" => typeof(DateTime),
                "RAW" when dataLength == 16 => typeof(Guid),
                "RAW" or "LONG RAW" or "BLOB" or "BFILE" => typeof(byte[]),
                _ => typeof(string),
            };
        }
    }
}
